apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: support-desk-backend
  template:
    metadata:
      labels:
        app: support-desk-backend
    spec:
      containers:
        - name: backend
          image: support-desk-proj-backend:latest
          ports:
            - containerPort: 8000
          env:
          - name: NODE_ENV
            value: "production"
          - name: MONGO_USER
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongo-user
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongo-password
          - name: MONGO_DATABASE
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongo-database
          - name: MONGO_URI
            value: mongodb://appuser:nguyenduy2004@mongodb-0.mongodb.default.svc.cluster.local:27017/supportdesk?authSource=supportdesk
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: support-desk-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
