apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
stringData:
  mongo-root-username: admin
  mongo-root-password: nguyenduy231104
  mongo-database: supportdesk
  mongo-user: appuser
  mongo-password: nguyenduy2004
